export const ALL_CATEGORIES_REQUEST = "ALL_CATEGORIES_REQUEST"
export const ALL_CATEGORIES_SUCCESS = "ALL_CATEGORIES_SUCCESS"
export const ALL_CATEGORIES_FAIL = "ALL_CATEGORIES_FAIL"

export const CREATE_CATEGORIES_REQUEST = "CREATE_CATEGORIES_REQUEST"
export const CREATE_CATEGORIES_SUCCESS = "CREATE_CATEGORIES_SUCCESS"
export const CREATE_CATEGORIES_FAIL = "CREATE_CATEGORIES_FAIL"

export const UPDATE_CATEGORIES_REQUEST = "UPDATE_CATEGORIES_REQUEST"
export const UPDATE_CATEGORIES_SUCCESS = "UPDATE_CATEGORIES_SUCCESS"
export const UPDATE_CATEGORIES_FAIL = "UPDATE_CATEGORIES_FAIL"

export const DELETE_CATEGORIES_REQUEST = "DELETE_CATEGORIES_REQUEST"
export const DELETE_CATEGORIES_SUCCESS = "DELETE_CATEGORIES_SUCCESS"
export const DELETE_CATEGORIES_FAIL = "DELETE_CATEGORIES_FAIL"
