export const PAYMENT_URL_REQUEST = "PAYMENT_URL_REQUEST"
export const PAYMENT_URL_SUCCESS = "PAYMENT_URL_SUCCESS"
export const PAYMENT_URL_FAIL = "PAYMENT_URL_FAIL"

export const PAYMENT_REQUEST = "PAYMENT_REQUEST"
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
export const PAYMENT_FAIL = "PAYMENT_FAIL"