export const ALL_SUBSCRIPTION_REQUEST = "ALL_SUBSCRIPTION_REQUEST"
export const ALL_SUBSCRIPTION_SUCCESS = "ALL_SUBSCRIPTION_SUCCESS"
export const ALL_SUBSCRIPTION_FAIL = "ALL_SUBSCRIPTION_FAIL"
export const ALL_SUBSCRIPTION_RESET = "ALL_SUBSCRIPTION_RESET"

export const CREATE_SUBSCRIPTION_REQUEST = "CREATE_SUBSCRIPTION_REQUEST"
export const CREATE_SUBSCRIPTION_SUCCESS = "CREATE_SUBSCRIPTION_SUCCESS"
export const CREATE_SUBSCRIPTION_FAIL = "CREATE_SUBSCRIPTION_FAIL"
export const CREATE_SUBSCRIPTION_RESET = "CREATE_SUBSCRIPTION_RESET"

export const UPDATE_SUBSCRIPTION_REQUEST = "UPDATE_SUBSCRIPTION_REQUEST"
export const UPDATE_SUBSCRIPTION_SUCCESS = "UPDATE_SUBSCRIPTION_SUCCESS"
export const UPDATE_SUBSCRIPTION_FAIL = "UPDATE_SUBSCRIPTION_FAIL"
export const UPDATE_SUBSCRIPTION_RESET = "UPDATE_SUBSCRIPTION_RESET"

export const DELETE_SUBSCRIPTION_REQUEST = "DELETE_SUBSCRIPTION_REQUEST"
export const DELETE_SUBSCRIPTION_SUCCESS = "DELETE_SUBSCRIPTION_SUCCESS"
export const DELETE_SUBSCRIPTION_FAIL = "DELETE_SUBSCRIPTION_FAIL"
export const DELETE_SUBSCRIPTION_RESET = "DELETE_SUBSCRIPTION_RESET"

export const PAYMENT_ORDER_REQUEST = "PAYMENT_ORDER_REQUEST"
export const PAYMENT_ORDER_SUCCESS = "PAYMENT_ORDER_SUCCESS"
export const PAYMENT_ORDER_FAIL = "PAYMENT_ORDER_FAIL"
export const PAYMENT_ORDER_RESET = "PAYMENT_ORDER_RESET"